const foodItem = [
    {
        id: 1,
        name: 'Cappuccino',
        category: 'Coffee',
        rating: 4.7,
        price: 4.00,
        img: 'images/menu/cappuccino.jpg',
        quantity: 1,
      },
      {
        id: 2,
        name: 'Latte',
        category: 'Coffee',
        rating: 4.6,
        price: 4.49,
        img: 'images/menu/latte.jpg',
        quantity: 1,
      },
      {
        id: 3,
        name: 'Espresso',
        category: 'Coffee',
        rating: 4.5,
        price: 3.00,
        img: 'images/menu/espresso.jpg',
        quantity: 1,
      },
      {
        id: 4,
        name: 'Mocha',
        category: 'Coffee',
        rating: 4.8,
        price: 4.00,
        img: 'images/menu/mocha.jpg',
        quantity: 1,
      },
      {
        id: 5,
        name: 'Iced Coffee',
        category: 'Coffee',
        rating: 4.4,
        price: 4.00,
        img: 'images/menu/iced-coffee.jpeg',
        quantity: 1,
      },
      {
        id: 6,
        name: 'Macchiato',
        category: 'Coffee',
        rating: 4.6,
        price: 4.29,
        img: 'images/menu/macchiato.jpg',
        quantity: 1,
      },
      {
        id: 7,
        name: 'Flat White',
        category: 'Coffee',
        rating: 4.5,
        price: 4.79,
        img: 'images/menu/flat-white.jpg',
        quantity: 1,
      },
      {
        id: 8,
        name: 'Americano',
        category: 'Coffee',
        rating: 4.6,
        price: 4.49,
        img: 'images/menu/americano.jpg',
        quantity: 1,
      },
      {
        id: 9,
        name: 'Cold Brew',
        category: 'Coffee',
        rating: 4.7,
        price: 5.00,
        img: 'images/menu/cold-brew.jpg',
        quantity: 1,
      },
      {
        id: 10,
        name: 'Turkish Coffee',
        category: 'Coffee',
        rating: 4.8,
        price: 4.00,
        img: 'images/menu/turkish-coffee.jpg',
        quantity: 1,
      },
      {
        id: 12,
        name: 'Irish Coffee',
        category: 'Coffee',
        rating: 4.7,
        price: 5.49,
        img: 'images/menu/irish-coffee.jpg',
        quantity: 1,
      },
      {
        id: 13,
        name: 'Caramel Macchiato',
        category: 'Coffee',
        rating: 4.8,
        price: 4.00,
        img: 'images/menu/caramel-macchiato.jpg',
        quantity: 1,
      },
      {
        id: 14,
        name: 'Pumpkin Spice Latte',
        category: 'Coffee',
        rating: 4.7,
        price: 5.29,
        img: 'images/menu/pumpkin-spice-latte.jpg',
        quantity: 1,
      },
      {
        id: 15,
        name: 'Honey Vanilla Latte',
        category: 'Coffee',
        rating: 4.6,
        price: 5.19,
        img: 'images/menu/honey-vanilla-latte.jpg',
        quantity: 1,
      },
      {
        id: 1,
        name: 'Croissant',
        category: 'Pastries',
        rating: 4.3,
        price: 2.00,
        img: 'images/menu/croissant.jpeg',
        quantity: 1,
      },
      {
        id: 2,
        name: 'Danish Pastry',
        category: 'Pastries',
        rating: 4.5,
        price: 3.49,
        img: 'images/menu/danish-pastry.jpeg',
        quantity: 1,
      },
      {
        id: 3,
        name: 'Chocolate Eclair',
        category: 'Pastries',
        rating: 4.4,
        price: 3.00,
        img: 'images/menu/chocolate-eclair.jpeg',
        quantity: 1,
      },
      {
        id: 4,
        name: 'Blueberry Scone',
        category: 'Pastries',
        rating: 4.6,
        price: 2.79,
        img: 'images/menu/blueberry-scone.jpeg',
        quantity: 1,
      },
      {
        id: 5,
        name: 'Almond Croissant',
        category: 'Pastries',
        rating: 4.7,
        price: 3.29,
        img: 'images/menu/almond-croissant.jpeg',
        quantity: 1,
      },
      {
        id: 6,
        name: 'Cinnamon Roll',
        category: 'Pastries',
        rating: 4.4,
        price: 3.49,
        img: 'images/menu/cinnamon-roll.jpeg',
        quantity: 1,
      },
      {
        id: 7,
        name: 'Strawberry Danish',
        category: 'Pastries',
        rating: 4.5,
        price: 3.29,
        img: 'images/menu/strawberry-danish.jpeg',
        quantity: 1,
      },
      {
        id: 8,
        name: 'Lemon Poppy Muffin',
        category: 'Pastries',
        rating: 4.3,
        price: 2.00,
        img: 'images/menu/lemon-muffin.jpeg',
        quantity: 1,
      },
      {
        id: 9,
        name: 'Apple Turnover',
        category: 'Pastries',
        rating: 4.6,
        price: 3.49,
        img: 'images/menu/apple-turnover.jpeg',
        quantity: 1,
      },
      {
        id: 10,
        name: 'Raspberry Danish',
        category: 'Pastries',
        rating: 4.5,
        price: 3.29,
        img: 'images/menu/raspberry-danish.jpeg',
        quantity: 1,
      },
      {
        id: 16,
        name: 'Chocolate Cake',
        category: 'Desserts',
        rating: 4.9,
        price: 6.00,
        img: 'images/menu/chocolate-cake.jpeg',
        quantity: 1,
      },
      {
        id: 17,
        name: 'Fruit Tart',
        category: 'Desserts',
        rating: 4.7,
        price: 5.00,
        img: 'images/menu/fruit-tart.jpeg',
        quantity: 1,
      },
      {
        id: 18,
        name: 'Tiramisu',
        category: 'Desserts',
        rating: 4.8,
        price: 6.49,
        img: 'images/menu/tiramisu.jpeg',
        quantity: 1,
      },
      {
        id: 19,
        name: 'Red Velvet Cupcake',
        category: 'Desserts',
        rating: 4.6,
        price: 3.00,
        img: 'images/menu/red-velvet-cupcake.jpeg',
        quantity: 1,
      },
      {
        id: 20,
        name: 'Panna Cotta',
        category: 'Desserts',
        rating: 4.5,
        price: 4.00,
        img: 'images/menu/panna-cotta.jpeg',
        quantity: 1,
      },
      {
        id: 21,
        name: 'Classic Pancakes',
        category: 'Breakfast',
        rating: 4.7,
        price: 7.00,
        img: 'images/menu/pancakes.jpeg',
        quantity: 1,
      },
      {
        id: 22,
        name: 'French Toast',
        category: 'Breakfast',
        rating: 4.6,
        price: 6.49,
        img: 'images/menu/french-toast.jpeg',
        quantity: 1,
      },
      {
        id: 23,
        name: 'Veggie Omelette',
        category: 'Breakfast',
        rating: 4.5,
        price: 8.00,
        img: 'images/menu/omelette.jpeg',
        quantity: 1,
      },
      {
        id: 24,
        name: 'Club Sandwich',
        category: 'Sandwiches',
        rating: 4.8,
        price: 7.00,
        img: 'images/menu/sandwich.jpeg',
        quantity: 1,
      },
      {
        id: 25,
        name: 'BLT Sandwich',
        category: 'Sandwiches',
        rating: 4.6,
        price: 6.00,
        img: 'images/menu/blt-sandwich.jpeg',
        quantity: 1,
      },
      {
        id: 26,
        name: 'Cheese Sandwich',
        category: 'Sandwiches',
        rating: 4.5,
        price: 5.00,
        img: 'images/menu/grilled-cheese.jpg',
        quantity: 1,
      },{
        id: 27,
        name: 'Strawberry Cheesecake',
        category: 'Desserts',
        rating: 4.9,
        price: 5.00,
        img: 'images/menu/strawberry-cheesecake.jpeg',
        quantity: 1,
      },
      {
        id: 28,
        name: 'Egg & Sausage Burrito',
        category: 'Breakfast',
        rating: 4.7,
        price: 6.00,
        img: 'images/menu/breakfast-burrito.jpeg',
        quantity: 1,
      },
      {
        id: 29,
        name: 'Turkey Club Sandwich',
        category: 'Sandwiches',
        rating: 4.8,
        price: 8,
        img: 'images/menu/turkey-club-sandwich.jpeg',
        quantity: 1,
      },
      {
        id: 30,
        name: 'Fruit Parfait',
        category: 'Desserts',
        rating: 4.6,
        price: 4,
        img: 'images/menu/fruit-parfait.jpg',
        quantity: 1,
      },
      {
        id: 31,
        name: 'Veggie Wrap',
        category: 'Sandwiches',
        rating: 4.7,
        price: 6,
        img: 'images/menu/veggie-wrap.jpeg',
        quantity: 1,
      },
      {
        id: 33,
        name: 'Spaghetti Carbonara',
        category: 'Pasta',
        rating: 4.5,
        price: 11.00,
        img: 'images/menu/spaghetti-carbonara.jpg',
        quantity: 1,
      },
      {
        id: 34,
        name: 'Chicken Alfredo',
        category: 'Pasta',
        rating: 4.6,
        price: 12.00,
        img: 'images/menu/chicken-alfredo.jpeg',
        quantity: 1,
      },
      {
        id: 35,
        name: 'Vegetable Lasagna',
        category: 'Pasta',
        rating: 4.4,
        price: 10.00,
        img: 'images/menu/vegetable-lasagna.jpg',
        quantity: 1,
      },
      {
        id: 36,
        name: 'Chicken Caesar Wrap',
        category: 'Wraps',
        rating: 4.7,
        price: 7.00,
        img: 'images/menu/chicken-caesar-wrap.jpeg',
        quantity: 1,
      },
      {
        id: 37,
        name: 'Mediterranean Wrap',
        category: 'Wraps',
        rating: 4.6,
        price: 6.00,
        img: 'images/menu/mediterranean-veggie-wrap.jpeg',
        quantity: 1,
      },
      {
        id: 30,
        name: 'Momos',
        category : 'chinese',
        rating : 4.3,
        price: 8,
        img: 'images/menu/cabbage-momos-.jpg',
        quantity: 1
    },
    {
        id: 31,
        name: 'Chicken Manchurian',
        category : 'chinese',
        rating : 4.3,
        price: 7,
        img: 'images/menu/ChickenManchurian.jpg',
        quantity: 1
    },
    {
        id: 32,
        name: 'Chili Chicken',
        category : 'chinese',
        rating : 4.3,
        price: 5,
        img: 'images/menu/Chili-Chicken.jpg',
        quantity: 1
    },
    {
        id: 33,
        name: 'Chowmein',
        category : 'chinese',
        rating : 4.3,
        price: 16,
        img: 'images/menu/chowmin.jpg',
        quantity: 1
    },
    {
        id: 34,
        name: 'Spring Roll',
        category : 'chinese',
        rating : 4.3,
        price: 14,
        img: 'images/menu/spring-rolls.jpg',
        quantity: 1
    },
    {
        id: 35,
        name: 'Szechuan Chicken',
        category : 'chinese',
        rating : 4.3,
        price: 10,
        img: 'images/menu/szechuan-chicken.jpg',
        quantity: 1
    },
    {
        id: 36,
        name: 'Fried Rice',
        category : 'chinese',
        rating : 4.3,
        price: 8,
        img: 'images/menu/veg-fried-rice.jpg',
        quantity: 1
    },
      {
        id: 38,
        name: 'Margherita Pizza',
        category: 'Pizza',
        rating: 4.8,
        price: 9.00,
        img: 'images/menu/margherita-pizza.jpeg',
        quantity: 1,
      },
      {
        id: 39,
        name: 'Pepperoni Pizza',
        category: 'Pizza',
        rating: 4.7,
        price: 10.00,
        img: 'images/menu/pepperoni-pizza.jpeg',
        quantity: 1,
      },
      {
        id: 40,
        name: 'Vegetarian Pizza',
        category: 'Pizza',
        rating: 4.6,
        price: 10.00,
        img: 'images/menu/vegetarian-pizza.jpeg',
        quantity: 1,
      },
      {
        id: 41,
        name: 'Meat Lovers Pizza',
        category: 'Pizza',
        rating: 4.7,
        price: 11.00,
        img: 'images/menu/meat-lovers-pizza.jpeg',
        quantity: 1,
      },
      {
        id: 42,
        name: 'Pesto Penne',
        category: 'Pasta',
        rating: 4.5,
        price: 9.00,
        img: 'images/menu/pesto-penne.jpeg',
        quantity: 1,
      },
      {
        id: 43,
        name: 'Hummus Wrap',
        category: 'Wraps',
        rating: 4.5,
        price: 6.00,
        img: 'images/menu/hummus-wrap.jpeg',
        quantity: 1,
      },
      {
        id: 44,
        name: 'BBQ Chicken Pizza',
        category: 'Pizza',
        rating: 4.8,
        price: 12.00,
        img: 'images/menu/bbq-chicken-pizza.jpeg',
        quantity: 1,
      }
    ];
  
  
  export { foodItem };
  